project:
  type: website
  resources:
    - "CNAME"

website:
  title: "blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - href: https://github.com/abrarsheikh
        text: Github
  search: true  # Enables search functionality

execute:
  freeze: auto

format:
  html:
    math: katex  # Use KaTeX for LaTeX math rendering
    theme:
      - cyborg
    highlight-style: github
    css: styles.css  # Include custom CSS for further customization
    toc: true  # Enable table of contents
    toc-depth: 3  # Set depth of the table of contents
    code-fold: false  # Keep all code blocks unfolded
    code-line-numbers: true  # Enable line numbers in code blocks
    number-sections: true
